### ISSUE TITLE
support Chinese gopher

### ISSUE THREAD

**Issue by polaris1119** [owenthereal/goup#2]
Thank you developing the tool. But China cannot access golang.org, so it is recommended that the `currentVersion` URL be configured with environment variables, such as https://golang.google.cn/VERSION?m=text.

**Comment by owenthereal** [comment]
@polaris1119 I see. Sure, I can make it possible to specify the golang host.

**Comment by polaris1119** [comment]
install  tip error：

```bash
fatal: unable to access 'https://go.googlesource.com/go/': Failed to connect to go.googlesource.com port 443: Operation timed out
Error: failed to clone git repository: exit status 128
```

Can you replace `go.googlesource.com` with `github.com`? Because `go.googlesource.com` is not accessible in China.

**Comment by polaris1119** [comment]
I wrote a post about goup: https://mp.weixin.qq.com/s/yTblk9Js1Zcq5aWVcYGjOA (Chinese)

**Comment by owenthereal** [comment]
@polaris1119 Thank you for the feedback on this project. I make the changes to allow swapping of Go host and downloading tip source from GitHub: https://github.com/owenthereal/goup/pull/4. However, building tip with a CL still downloads source from googlesource.com because CL is a googlesource concept.
